### ISSUE TITLE
NODE problem

### ISSUE THREAD

**Issue by fmagrosoto** [zaggino/brackets-git#979]
Hello... there is an isue with Brackets and NodeJS.
![bracketserro](https://cloud.githubusercontent.com/assets/2541316/6882488/34e48414-d54c-11e4-85d7-bfe74eef65a5.png)
I cant' fix it with just close and reopen.

**Comment by zaggino** [comment]
You'll need to provide a console log, but as said in the error, this is probably a problem of another extension breaking connection to node.js

**Comment by ASheppardWork** [comment]
I have the same issue.  After upgrading to the latest Brackets version on Friday 3/27/2015.  Now when I want to open more than one instance of Brackets and use the git plug-in; I get the same Node.JS issue as above.  I removed all my extensions, and then only added back brackets-git and the problem still persists.  Have done numerous re-starts just in case.  Screen shots and error log follow.


![brackets-git-issue-1](https://cloud.githubusercontent.com/assets/9010325/6900911/5b6be580-d6cf-11e4-9b10-ae1e7bdaefea.png)
![brackets-git-issue-2](https://cloud.githubusercontent.com/assets/9010325/6900914/5fa341de-d6cf-11e4-84d2-d2aaae4b19b3.png)
![brackets-git-issue-3](https://cloud.githubusercontent.com/assets/9010325/6900916/631a7da0-d6cf-11e4-8df4-5165a9e8d1ba.png)
![brackets-git-issue-4](https://cloud.githubusercontent.com/assets/9010325/6900922/665f95ea-d6cf-11e4-9220-7bcff678e739.png)

**Comment by zaggino** [comment]
You can't have more than one Brackets open at a time: https://github.com/zaggino/brackets-git/issues/971

**Comment by ASheppardWork** [comment]
I will go to the adobe brackets forum to list this issue.  For others who may have seen this, it happened only after I upgraded to the latest version put out in Feb 2015.  Before then, I was able to open multiple instances and use all the plugins.  Thank you.

**Comment by zaggino** [comment]
I was wrong - partially: You can do `Debug > New Brackets Window` to work around this.

**Comment by ASheppardWork** [comment]
Thank you @zaggino I rolled by my install of Brackets to ver 1.0.0-15191 and Brackets Git 0.14.9 and the problem has been resolved.  I will wait and see if Brackets releases some sort of fix/patch.

**Comment by skalka7** [comment]
I think this issue is related to some scss extension, like some linter. I don't know how I can be more precise, but I've seen that on a fresh Brackets installation (on ubuntu) issue first time occurred when scss linter found a problem on my code. Then it's impossible to beck to normality, even uninstalling extensions by deleting folders doesn't solve problems. For example I can't install Brackets Git again.
I hope this helps.

**Comment by zaggino** [comment]
This is fixed in https://github.com/zaggino/brackets-electron/releases
